Fix holidays issue when checking equality between dates
ipsosante/ISHolidays pull request #1
Opened 2019-01-03 16:23 UTC by wildine

2019-01-04 11:10 UTC, guillaumealgis requested changes

2019-01-04 11:10 UTC, guillaumealgis commented on ISHolidays/NSDate+ISHolidays.h
> +- (BOOL)checkEqualityWithoutTimeWith:(NSDate *)date;
Je pense que ce serait bien d'avoir un cohérence avec `-[isEqualToDate:]`, qui fait quasiment là même opération (et de manière générale c'est plutôt une bonne pratique de commencer un méthode qui retourne un `BOOL` par `isXXX`).

Que penses-tu de `isEqualToDateWithoutTime:` ou `isEqualToDateExcludingTime:` ?

2019-01-04 11:10 UTC, guillaumealgis commented on ISHolidays/NSDate+ISHolidays.h
> +- (BOOL)checkEqualityWithoutTimeWith:(NSDate *)date;
Je pense aussi que ce serait bien de séparer cette méthode dans une autre category. `-[isHoliday]` et `-[localizedHolidayName]` sont des méthodes utilitaires qui sont fournies à l'utilisateur de la lib, alors que la nouvelle méthode de comparaison de dates est liée au fonctionnement interne de la lib et n'a pas vocation à être utilisée par l'utilisateur final (elle serait marquée `internal` en Swift je pense).

2019-01-04 11:10 UTC, guillaumealgis commented on ISHolidaysTests/ISHolidaysFRTests.m
> +    self.dateComponents.hour = 9;
Je pense que ce serait bien de garder les tests actuels, mais de rajouter pour chaque jour férié un test supplémentaire avec un "time" différent de `00:00:00`.

2019-01-07 08:44 UTC, wildine commented on ISHolidays/NSDate+ISHolidays.h
> +- (BOOL)checkEqualityWithoutTimeWith:(NSDate *)date;
Oui tu as raison, j'aime bien `isEqualToDateExcludingTime` :)

2019-01-07 10:56 UTC, wildine commented on ISHolidays/NSDate+ISHolidays.h
> +- (BOOL)checkEqualityWithoutTimeWith:(NSDate *)date;
J'ai séparée et mis la méthode `isEqualToDateExcludingTime` dans un fichier à part : `NSDate+Compare`.

2019-01-07 10:56 UTC, guillaumealgis approved these changes

2019-01-07 10:57 UTC, merged